In [1]:
import duckdb

con = duckdb.connect("../data/gold/gold.duckdb", read_only=True)

con.sql("SHOW TABLES").df()

                                     name
0                 mart_area_macro_summary
1                     mart_daily_activity
2          mart_directional_macro_summary
3                   mart_overview_summary
4                    mart_region_activity
5               mart_weapon_model_summary
6                mart_weapon_type_summary
7                   silver_attack_regions
8                          silver_attacks
9                 silver_weapon_reference
10               vw_dashboard_area_macros
11         vw_dashboard_area_macros_daily
12            vw_dashboard_daily_activity
13        vw_dashboard_directional_macros
14  vw_dashboard_directional_macros_daily
15                  vw_dashboard_overview
16                vw_dashboard_region_map
17          vw_dashboard_region_map_daily
18             vw_dashboard_weapon_models
19       vw_dashboard_weapon_models_daily
20              vw_dashboard_weapon_types
21        vw_dashboard_weapon_types_daily

In [2]:
con.sql("SELECT * FROM mart_overview_summary").df()

,first_event_date,last_event_date,total_attack_rows,distinct_event_dates,distinct_weapon_models,distinct_weapon_categories,total_launched,total_destroyed,total_not_reach_goal,total_still_attacking,nationwide_launched_total,specific_area_launched_total,unknown_target_rows,unmatched_weapon_reference_rows,top_uav_weapon_model_key,top_uav_launched,top_cruise_missile_weapon_model_key,top_cruise_missile_launched,top_ballistic_missile_weapon_model_key,top_ballistic_missile_launched
0,2022-09-28,2026-04-18,3617,1072,71,7,103094.0,75892.0,13053.0,516.0,92478.0,3725.0,30.0,9.0,shahed-136/131,89712.0,x-101/x-555,2014.0,iskander-m,486.0

In [ ]:
con.sql("""
SELECT *
FROM daily.mart_region_daily
LIMIT 5;
""").df()

,event_date,attack_rows,distinct_weapon_models,launched_total,destroyed_total,not_reach_goal_total,still_attacking_total,launched_7d_avg,destroyed_7d_avg
0,2022-09-28,2,2,8.0,7.0,0.0,0.0,8.000000,7.000000
1,2022-09-29,1,1,7.0,5.0,0.0,0.0,7.500000,6.000000
2,2022-09-30,1,1,3.0,3.0,0.0,0.0,6.000000,5.000000
3,2022-10-01,1,1,1.0,1.0,0.0,0.0,4.750000,4.000000
4,2022-10-02,1,1,7.0,5.0,0.0,0.0,5.200000,4.200000
5,2022-10-05,3,2,8.0,8.0,0.0,0.0,5.666667,4.833333
6,2022-10-06,6,3,17.0,17.0,0.0,0.0,7.285714,6.571429
7,2022-10-07,1,1,3.0,3.0,0.0,0.0,6.571429,6.000000
8,2022-10-08,2,2,3.0,3.0,0.0,0.0,6.000000,5.714286
9,2022-10-09,3,3,22.0,1.0,0.0,0.0,8.714286,5.428571
10,2022-10-10,3,3,108.0,56.0,0.0,0.0,24.000000,13.285714
11,2022-10-11,4,2,62.0,54.0,0.0,0.0,31.857143,20.285714
12,2022-10-12,2,2,19.0,19.0,0.0,0.0,33.428571,21.857143
13,2022-10-13,2,2,11.0,11.0,0.0,0.0,32.571429,21.000000
14,2022-10-14,1,1,8.0,8.0,0.0,0.0,33.285714,21.714286
15,2022-10-15,1,1,6.0,6.0,0.0,0.0,33.714286,22.142857
16,2022-10-16,1,1,11.0,11.0,0.0,0.0,32.142857,23.571429
17,2022-10-17,5,3,39.0,39.0,0.0,0.0,22.285714,21.142857
18,2022-10-18,3,3,11.0,11.0,0.0,0.0,15.000000,15.000000
19,2022-10-19,3,2,29.0,27.0,0.0,0.0,16.428571,16.142857

In [18]:
con.sql("""
SELECT *
FROM daily.mart_region_daily
LIMIT 5;
""").df()

,event_date,area_region,reporting_region,lat,lon,area_kind,active_days,attack_rows,exploded_region_rows,launched_total_exploded,destroyed_total_exploded,launched_total_allocated,destroyed_total_allocated
0,2022-09-28,Dnipropetrovsk oblast,Dnipropetrovsk oblast,48.47,35.04,oblast,1,1,1,5.0,4.0,2.5,2.0
1,2022-09-28,Zaporizhzhia oblast,Zaporizhzhia oblast,47.84,35.14,oblast,1,1,1,5.0,4.0,2.5,2.0
2,2022-09-29,Mykolaiv oblast,Mykolaiv oblast,46.97,31.99,oblast,1,1,1,7.0,5.0,3.5,2.5
3,2022-09-29,Odesa oblast,Odesa oblast,46.48,30.72,oblast,1,1,1,7.0,5.0,3.5,2.5
4,2022-10-02,Mykolaiv oblast,Mykolaiv oblast,46.97,31.99,oblast,1,1,1,7.0,5.0,7.0,5.0

In [5]:
con.sql("""
SELECT *
FROM mart_area_macro_summary
ORDER BY launched_total DESC
""").df()

,area_macro,target_scope,attack_rows,active_days,launched_total,destroyed_total,air_defense_success_pct,launched_share_pct
0,nationwide,nationwide,1498,823,92478.0,66768.0,72.20,89.70
1,south,directional_or_other_macro,979,527,6006.0,5981.0,99.58,5.83
2,south,specific_area_rows,527,339,1431.0,947.0,66.18,1.39
3,multi,specific_area_rows,57,50,875.0,589.0,67.31,0.85
4,north,specific_area_rows,53,42,572.0,514.0,89.86,0.55
5,center-east,specific_area_rows,175,141,314.0,214.0,68.15,0.30
6,east,specific_area_rows,97,79,295.0,97.0,32.88,0.29
7,east,directional_or_other_macro,91,62,281.0,175.0,62.28,0.27
8,multi,directional_or_other_macro,9,9,241.0,187.0,77.59,0.23
9,unknown,unknown,30,21,192.0,133.0,69.27,0.19
10,west,directional_or_other_macro,8,8,94.0,91.0,96.81,0.09
11,center-west,specific_area_rows,14,13,73.0,51.0,69.86,0.07
12,south-east,specific_area_rows,29,21,66.0,29.0,43.94,0.06
13,north-east,specific_area_rows,20,18,54.0,25.0,46.30,0.05
14,south-east,directional_or_other_macro,5,5,34.0,33.0,97.06,0.03
15,west,specific_area_rows,8,8,32.0,16.0,50.00,0.03
16,north,directional_or_other_macro,7,7,28.0,21.0,75.00,0.03
17,center,specific_area_rows,3,3,7.0,5.0,71.43,0.01
18,international,specific_area_rows,2,2,6.0,1.0,16.67,0.01
19,front line,directional_or_other_macro,2,1,5.0,5.0,100.00,0.00
20,north-east,directional_or_other_macro,2,1,5.0,5.0,100.00,0.00
21,center,directional_or_other_macro,1,1,5.0,5.0,100.00,0.00

In [17]:
con.sql("""
SELECT *
FROM daily.mart_region_daily
LIMIT 5;
""").df()

,event_date,area_region,reporting_region,lat,lon,area_kind,active_days,attack_rows,exploded_region_rows,launched_total_exploded,destroyed_total_exploded,launched_total_allocated,destroyed_total_allocated
0,2022-09-28,Dnipropetrovsk oblast,Dnipropetrovsk oblast,48.47,35.04,oblast,1,1,1,5.0,4.0,2.5,2.0
1,2022-09-28,Zaporizhzhia oblast,Zaporizhzhia oblast,47.84,35.14,oblast,1,1,1,5.0,4.0,2.5,2.0
2,2022-09-29,Mykolaiv oblast,Mykolaiv oblast,46.97,31.99,oblast,1,1,1,7.0,5.0,3.5,2.5
3,2022-09-29,Odesa oblast,Odesa oblast,46.48,30.72,oblast,1,1,1,7.0,5.0,3.5,2.5
4,2022-10-02,Mykolaiv oblast,Mykolaiv oblast,46.97,31.99,oblast,1,1,1,7.0,5.0,7.0,5.0

In [7]:
con.sql("""
SELECT table_schema, table_name
FROM information_schema.tables
ORDER BY table_schema, table_name;
""").df()

   table_schema                             table_name
0         daily                  mart_area_macro_daily
1         daily           mart_directional_macro_daily
2         daily                      mart_region_daily
3         daily                mart_weapon_model_daily
4         daily                 mart_weapon_type_daily
5          main                mart_area_macro_summary
6          main                    mart_daily_activity
7          main         mart_directional_macro_summary
8          main                  mart_overview_summary
9          main                   mart_region_activity
10         main              mart_weapon_model_summary
11         main               mart_weapon_type_summary
12         main                  silver_attack_regions
13         main                         silver_attacks
14         main                silver_weapon_reference
15         main               vw_dashboard_area_macros
16         main         vw_dashboard_area_macros_daily
17         main            vw_dashboard_daily_activity
18         main        vw_dashboard_directional_macros
19         main  vw_dashboard_directional_macros_daily
20         main                  vw_dashboard_overview
21         main                vw_dashboard_region_map
22         main          vw_dashboard_region_map_daily
23         main             vw_dashboard_weapon_models
24         main       vw_dashboard_weapon_models_daily
25         main              vw_dashboard_weapon_types
26         main        vw_dashboard_weapon_types_daily

In [8]:
con.sql("SELECT * FROM vw_dashboard_overview LIMIT 20").df()

,first_event_date,last_event_date,total_attack_rows,distinct_event_dates,distinct_weapon_models,distinct_weapon_categories,total_launched,total_destroyed,total_not_reach_goal,total_still_attacking,nationwide_launched_total,specific_area_launched_total,unknown_target_rows,unmatched_weapon_reference_rows,top_uav_weapon_model_key,top_uav_launched,top_cruise_missile_weapon_model_key,top_cruise_missile_launched,top_ballistic_missile_weapon_model_key,top_ballistic_missile_launched
0,2022-09-28,2026-04-18,3617,1072,71,7,103094.0,75892.0,13053.0,516.0,92478.0,3725.0,30.0,9.0,shahed-136/131,89712.0,x-101/x-555,2014.0,iskander-m,486.0

In [9]:
con.sql("SELECT * FROM silver_attacks LIMIT 5 ").df()

,source_file,source_row_number,event_date,time_start,time_end,weapon_model,weapon_model_key,weapon_category,weapon_type,weapon_national_origin,...,num_hit_location,num_fall_fragment_location,carrier,turbojet,turbojet_destroyed,affected_region,destroyed_details,launched_details,launch_place_details,source
0,missile_attacks_daily.csv,1,2026-04-18,2026-04-18 17:30,2026-04-19 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,18,8,<NA>,<NA>,<NA>,,"{'south': 23, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid0MeNK3NXQXEE3UZmCEd9ACbScZTX...
1,missile_attacks_daily.csv,2,2026-04-17,2026-04-17 18:00,2026-04-18 08:30,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,17,9,<NA>,<NA>,<NA>,,"{'south': 56, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid02SbNVam4xqrQuM1pWKBGqKsMprJ...
2,missile_attacks_daily.csv,3,2026-04-18,2026-04-18,2026-04-18,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid02QHv7o6nNNq7wsjui4ixPYDG...
3,missile_attacks_daily.csv,4,2026-04-16,2026-04-16 18:00,2026-04-17 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,8,4,<NA>,<NA>,<NA>,,"{'south': 86, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid0fWmfYz3KEHzAskn2FhyBgruZ2wR...
4,missile_attacks_daily.csv,5,2026-04-16,2026-04-16 18:00,2026-04-17 08:00,Iskander-M,iskander-m,ballistic missile,"TV-guided, tactical",russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,kpszsu/posts/pfbid0fWmfYz3KEHzAskn2FhyBgruZ2wR...

In [10]:
con.sql("SELECT * FROM silver_attacks LIMIT 5 ").df()

,source_file,source_row_number,event_date,time_start,time_end,weapon_model,weapon_model_key,weapon_category,weapon_type,weapon_national_origin,...,num_hit_location,num_fall_fragment_location,carrier,turbojet,turbojet_destroyed,affected_region,destroyed_details,launched_details,launch_place_details,source
0,missile_attacks_daily.csv,1,2026-04-18,2026-04-18 17:30,2026-04-19 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,18,8,<NA>,<NA>,<NA>,,"{'south': 23, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid0MeNK3NXQXEE3UZmCEd9ACbScZTX...
1,missile_attacks_daily.csv,2,2026-04-17,2026-04-17 18:00,2026-04-18 08:30,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,17,9,<NA>,<NA>,<NA>,,"{'south': 56, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid02SbNVam4xqrQuM1pWKBGqKsMprJ...
2,missile_attacks_daily.csv,3,2026-04-18,2026-04-18,2026-04-18,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid02QHv7o6nNNq7wsjui4ixPYDG...
3,missile_attacks_daily.csv,4,2026-04-16,2026-04-16 18:00,2026-04-17 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,8,4,<NA>,<NA>,<NA>,,"{'south': 86, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid0fWmfYz3KEHzAskn2FhyBgruZ2wR...
4,missile_attacks_daily.csv,5,2026-04-16,2026-04-16 18:00,2026-04-17 08:00,Iskander-M,iskander-m,ballistic missile,"TV-guided, tactical",russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,kpszsu/posts/pfbid0fWmfYz3KEHzAskn2FhyBgruZ2wR...

In [11]:
con.sql("SELECT * FROM vw_dashboard_region_map").df()

,area_region,reporting_region,attack_rows,exploded_region_rows,source_region_count,active_days,launched_total_exploded,destroyed_total_exploded,launched_total_allocated,destroyed_total_allocated,lat,lon,area_kind,air_defense_success_pct,launched_share_pct
0,Odesa oblast,Odesa oblast,255,255,3,209,1378.0,887.0,1034.17,642.00,46.48,30.72,oblast,62.08,27.76
1,Dnipropetrovsk oblast,Dnipropetrovsk oblast,175,175,3,146,528.0,391.0,356.08,267.00,48.47,35.04,oblast,74.98,9.56
2,Kherson oblast,Kherson oblast,172,172,2,114,347.0,276.0,275.25,222.33,46.64,32.62,oblast,80.78,7.39
3,Mykolaiv oblast,Mykolaiv oblast,160,160,2,133,696.0,519.0,420.92,301.25,46.97,31.99,oblast,71.57,11.30
4,Kharkiv oblast,Kharkiv oblast,85,85,2,67,339.0,131.0,269.33,110.33,49.99,36.23,oblast,40.97,7.23
5,Kyiv oblast,Kyiv oblast,60,60,2,46,862.0,703.0,697.50,601.83,50.45,30.52,oblast,86.28,18.72
6,Zaporizhzhia oblast,Zaporizhzhia oblast,43,43,2,34,250.0,130.0,137.42,66.08,47.84,35.14,oblast,48.09,3.69
7,Sumy oblast,Sumy oblast,38,38,2,31,247.0,140.0,136.00,72.00,50.91,34.80,oblast,52.94,3.65
8,Poltava oblast,Poltava oblast,30,30,1,25,135.0,83.0,87.33,45.42,49.59,34.55,oblast,52.00,2.34
9,Donetsk oblast,Donetsk oblast,27,27,2,27,88.0,3.0,73.50,3.00,48.72,37.55,oblast,4.08,1.97
10,Khmelnytskyi oblast,Khmelnytskyi oblast,20,20,2,19,170.0,138.0,109.33,83.67,49.42,26.99,oblast,76.52,2.94
11,Chernihiv oblast,Chernihiv oblast,12,12,1,11,30.0,6.0,23.67,4.67,51.50,31.29,oblast,19.72,0.64
12,Kirovohrad oblast,Kirovohrad oblast,7,7,1,7,75.0,62.0,27.83,24.08,48.51,32.26,oblast,86.53,0.75
13,Lviv oblast,Lviv oblast,6,6,1,6,22.0,9.0,22.00,9.00,49.84,24.03,oblast,40.91,0.59
14,Vinnytsia oblast,Vinnytsia oblast,5,5,1,5,71.0,59.0,27.00,22.33,49.23,28.48,oblast,82.72,0.72
15,Kursk oblast,Kursk oblast,3,3,1,3,12.0,1.0,9.00,1.00,51.73,36.19,foreign_oblast,11.11,0.24
16,Cherkasy oblast,Cherkasy oblast,2,2,1,2,22.0,15.0,8.67,5.00,49.44,32.06,oblast,57.69,0.23
17,Rivne oblast,Rivne oblast,1,1,1,1,6.0,6.0,3.00,3.00,50.62,26.25,oblast,100.00,0.08
18,Volyn oblast,Volyn oblast,1,1,1,1,6.0,6.0,3.00,3.00,50.75,25.33,oblast,100.00,0.08
19,Ivano-Frankivsk oblast,Ivano-Frankivsk oblast,1,1,1,1,4.0,1.0,4.00,1.00,48.92,24.71,oblast,25.00,0.11

In [12]:
con.sql("""
SELECT *
FROM mart_area_macro_summary
LIMIT 2
""").df()

,area_macro,target_scope,attack_rows,active_days,launched_total,destroyed_total,air_defense_success_pct,launched_share_pct
0,nationwide,nationwide,1498,823,92478.0,66768.0,72.20,89.70
1,south,directional_or_other_macro,979,527,6006.0,5981.0,99.58,5.83

In [13]:
con.sql("""
SELECT *
FROM mart_directional_macro_summary
LIMIT 1
""").df()

,area_macro,attack_rows,active_days,launched_total,destroyed_total,lat,lon,air_defense_success_pct,launched_share_pct
0,south,1506,731,7437.0,6928.0,46.8,31.5,93.16,79.99

In [14]:
con.sql("""
SELECT *
FROM mart_weapon_model_daily
LIMIT 1
""").df()

CatalogException: Catalog Error: Table with name mart_weapon_model_daily does not exist!
Did you mean "daily.mart_weapon_model_daily"?