In [1]:
import duckdb

con = duckdb.connect("../data/gold/gold.duckdb", read_only=True)

con.sql("SHOW TABLES").df()

                               name
0           mart_area_macro_summary
1               mart_daily_activity
2    mart_directional_macro_summary
3             mart_overview_summary
4              mart_region_activity
5         mart_weapon_model_summary
6          mart_weapon_type_summary
7             silver_attack_regions
8                    silver_attacks
9           silver_weapon_reference
10         vw_dashboard_area_macros
11      vw_dashboard_daily_activity
12  vw_dashboard_directional_macros
13            vw_dashboard_overview
14          vw_dashboard_region_map
15       vw_dashboard_weapon_models
16        vw_dashboard_weapon_types

In [2]:
con.sql("SELECT * FROM mart_overview_summary").df()

,first_event_date,last_event_date,total_attack_rows,distinct_event_dates,distinct_weapon_models,distinct_weapon_categories,total_launched,total_destroyed,total_not_reach_goal,total_still_attacking,nationwide_launched_total,specific_area_launched_total,unknown_target_rows,unmatched_weapon_reference_rows
0,2022-09-28,2026-04-10,3597,1066,70,7,100825.0,73795.0,13052.0,499.0,90589.0,3724.0,30.0,9.0

In [3]:
con.sql("""
SELECT *
FROM mart_daily_activity
ORDER BY event_date
LIMIT 20
""").df()

,event_date,attack_rows,distinct_weapon_models,launched_total,destroyed_total,not_reach_goal_total,still_attacking_total,launched_7d_avg,destroyed_7d_avg
0,2022-09-28,2,2,8.0,7.0,0.0,0.0,8.000000,7.000000
1,2022-09-29,1,1,7.0,5.0,0.0,0.0,7.500000,6.000000
2,2022-09-30,1,1,3.0,3.0,0.0,0.0,6.000000,5.000000
3,2022-10-01,1,1,1.0,1.0,0.0,0.0,4.750000,4.000000
4,2022-10-02,1,1,7.0,5.0,0.0,0.0,5.200000,4.200000
5,2022-10-05,3,2,8.0,8.0,0.0,0.0,5.666667,4.833333
6,2022-10-06,6,3,17.0,17.0,0.0,0.0,7.285714,6.571429
7,2022-10-07,1,1,3.0,3.0,0.0,0.0,6.571429,6.000000
8,2022-10-08,2,2,3.0,3.0,0.0,0.0,6.000000,5.714286
9,2022-10-09,3,3,22.0,1.0,0.0,0.0,8.714286,5.428571
10,2022-10-10,3,3,108.0,56.0,0.0,0.0,24.000000,13.285714
11,2022-10-11,4,2,62.0,54.0,0.0,0.0,31.857143,20.285714
12,2022-10-12,2,2,19.0,19.0,0.0,0.0,33.428571,21.857143
13,2022-10-13,2,2,11.0,11.0,0.0,0.0,32.571429,21.000000
14,2022-10-14,1,1,8.0,8.0,0.0,0.0,33.285714,21.714286
15,2022-10-15,1,1,6.0,6.0,0.0,0.0,33.714286,22.142857
16,2022-10-16,1,1,11.0,11.0,0.0,0.0,32.142857,23.571429
17,2022-10-17,5,3,39.0,39.0,0.0,0.0,22.285714,21.142857
18,2022-10-18,3,3,11.0,11.0,0.0,0.0,15.000000,15.000000
19,2022-10-19,3,2,29.0,27.0,0.0,0.0,16.428571,16.142857

In [4]:
con.sql("""
SELECT *
FROM mart_daily_activity
ORDER BY event_date
LIMIT 20
""").df()

,event_date,attack_rows,distinct_weapon_models,launched_total,destroyed_total,not_reach_goal_total,still_attacking_total,launched_7d_avg,destroyed_7d_avg
0,2022-09-28,2,2,8.0,7.0,0.0,0.0,8.000000,7.000000
1,2022-09-29,1,1,7.0,5.0,0.0,0.0,7.500000,6.000000
2,2022-09-30,1,1,3.0,3.0,0.0,0.0,6.000000,5.000000
3,2022-10-01,1,1,1.0,1.0,0.0,0.0,4.750000,4.000000
4,2022-10-02,1,1,7.0,5.0,0.0,0.0,5.200000,4.200000
5,2022-10-05,3,2,8.0,8.0,0.0,0.0,5.666667,4.833333
6,2022-10-06,6,3,17.0,17.0,0.0,0.0,7.285714,6.571429
7,2022-10-07,1,1,3.0,3.0,0.0,0.0,6.571429,6.000000
8,2022-10-08,2,2,3.0,3.0,0.0,0.0,6.000000,5.714286
9,2022-10-09,3,3,22.0,1.0,0.0,0.0,8.714286,5.428571
10,2022-10-10,3,3,108.0,56.0,0.0,0.0,24.000000,13.285714
11,2022-10-11,4,2,62.0,54.0,0.0,0.0,31.857143,20.285714
12,2022-10-12,2,2,19.0,19.0,0.0,0.0,33.428571,21.857143
13,2022-10-13,2,2,11.0,11.0,0.0,0.0,32.571429,21.000000
14,2022-10-14,1,1,8.0,8.0,0.0,0.0,33.285714,21.714286
15,2022-10-15,1,1,6.0,6.0,0.0,0.0,33.714286,22.142857
16,2022-10-16,1,1,11.0,11.0,0.0,0.0,32.142857,23.571429
17,2022-10-17,5,3,39.0,39.0,0.0,0.0,22.285714,21.142857
18,2022-10-18,3,3,11.0,11.0,0.0,0.0,15.000000,15.000000
19,2022-10-19,3,2,29.0,27.0,0.0,0.0,16.428571,16.142857

In [ ]:
1