In [1]:
import duckdb

con = duckdb.connect("../data/gold/gold.duckdb", read_only=True)

con.sql("SHOW TABLES").df()

                               name
0           mart_area_macro_summary
1               mart_daily_activity
2    mart_directional_macro_summary
3             mart_overview_summary
4              mart_region_activity
5         mart_weapon_model_summary
6          mart_weapon_type_summary
7             silver_attack_regions
8                    silver_attacks
9           silver_weapon_reference
10         vw_dashboard_area_macros
11      vw_dashboard_daily_activity
12  vw_dashboard_directional_macros
13            vw_dashboard_overview
14          vw_dashboard_region_map
15       vw_dashboard_weapon_models
16        vw_dashboard_weapon_types

In [2]:
con.sql("SELECT * FROM mart_overview_summary").df()

,first_event_date,last_event_date,total_attack_rows,distinct_event_dates,distinct_weapon_models,distinct_weapon_categories,total_launched,total_destroyed,total_not_reach_goal,total_still_attacking,nationwide_launched_total,specific_area_launched_total,unknown_target_rows,unmatched_weapon_reference_rows
0,2022-09-28,2026-04-10,3597,1066,70,7,100825.0,73795.0,13052.0,499.0,90589.0,3724.0,30.0,9.0

In [3]:
con.sql("""
SELECT *
FROM mart_daily_activity
ORDER BY event_date
LIMIT 20
""").df()

,event_date,attack_rows,distinct_weapon_models,launched_total,destroyed_total,not_reach_goal_total,still_attacking_total,launched_7d_avg,destroyed_7d_avg
0,2022-09-28,2,2,8.0,7.0,0.0,0.0,8.000000,7.000000
1,2022-09-29,1,1,7.0,5.0,0.0,0.0,7.500000,6.000000
2,2022-09-30,1,1,3.0,3.0,0.0,0.0,6.000000,5.000000
3,2022-10-01,1,1,1.0,1.0,0.0,0.0,4.750000,4.000000
4,2022-10-02,1,1,7.0,5.0,0.0,0.0,5.200000,4.200000
5,2022-10-05,3,2,8.0,8.0,0.0,0.0,5.666667,4.833333
6,2022-10-06,6,3,17.0,17.0,0.0,0.0,7.285714,6.571429
7,2022-10-07,1,1,3.0,3.0,0.0,0.0,6.571429,6.000000
8,2022-10-08,2,2,3.0,3.0,0.0,0.0,6.000000,5.714286
9,2022-10-09,3,3,22.0,1.0,0.0,0.0,8.714286,5.428571
10,2022-10-10,3,3,108.0,56.0,0.0,0.0,24.000000,13.285714
11,2022-10-11,4,2,62.0,54.0,0.0,0.0,31.857143,20.285714
12,2022-10-12,2,2,19.0,19.0,0.0,0.0,33.428571,21.857143
13,2022-10-13,2,2,11.0,11.0,0.0,0.0,32.571429,21.000000
14,2022-10-14,1,1,8.0,8.0,0.0,0.0,33.285714,21.714286
15,2022-10-15,1,1,6.0,6.0,0.0,0.0,33.714286,22.142857
16,2022-10-16,1,1,11.0,11.0,0.0,0.0,32.142857,23.571429
17,2022-10-17,5,3,39.0,39.0,0.0,0.0,22.285714,21.142857
18,2022-10-18,3,3,11.0,11.0,0.0,0.0,15.000000,15.000000
19,2022-10-19,3,2,29.0,27.0,0.0,0.0,16.428571,16.142857

In [5]:
con.sql("""
SELECT *
FROM mart_weapon_model_summary
ORDER BY launched_total DESC
LIMIT 20
""").df()

,weapon_model,weapon_category,weapon_type,attack_rows,active_days,launched_total,destroyed_total,matched_rows,unmatched_rows,reference_coverage_pct,launched_share_pct,destroyed_to_launched_pct,first_seen,last_seen
0,Shahed-136/131,UAV,loitering munition,991,913,87875.0,63761.0,991.0,0.0,100.0,87.16,72.56,2022-09-29,2026-04-10
1,Unknown,Mixed,Unknown type,290,285,3471.0,3390.0,290.0,0.0,100.0,3.44,97.67,2022-10-08,2026-04-10
2,X-101/X-555,cruise missile,air-launched,102,101,1994.0,1708.0,102.0,0.0,100.0,1.98,85.66,2022-10-18,2026-04-03
3,Молнія,UAV,Unknown type,112,112,811.0,811.0,112.0,0.0,100.0,0.80,100.00,2025-01-09,2026-02-17
4,X-101/X-555 and Kalibr,cruise missile,Unknown type,9,9,643.0,508.0,9.0,0.0,100.0,0.64,79.00,2022-10-10,2025-05-25
5,Kalibr,cruise missile,Unknown type,73,72,557.0,433.0,73.0,0.0,100.0,0.55,77.74,2022-10-13,2026-03-14
6,Iskander-M,ballistic missile,"TV-guided, tactical",264,236,482.0,71.0,264.0,0.0,100.0,0.48,14.73,2023-05-22,2026-04-02
7,Reconnaissance UAV,UAV,reconnaissance,200,199,460.0,459.0,200.0,0.0,100.0,0.46,99.78,2022-09-28,2026-03-29
8,Iskander-M/KN-23,ballistic missile,Unknown type,83,78,364.0,90.0,83.0,0.0,100.0,0.36,24.73,2024-02-15,2025-12-13
9,Lancet,UAV,loitering munition,143,143,355.0,355.0,143.0,0.0,100.0,0.35,100.00,2022-10-12,2025-10-25
10,C-300,surface-to-air missile,santi-ballistic missile,80,80,345.0,2.0,80.0,0.0,100.0,0.34,0.58,2022-10-09,2025-11-03
11,ZALA,UAV,reconnaissance,175,162,309.0,308.0,175.0,0.0,100.0,0.31,99.68,2023-05-08,2025-11-15
12,X-59/X-69,cruise missile,Unknown type,107,100,292.0,191.0,107.0,0.0,100.0,0.29,65.41,2024-04-19,2026-03-23
13,X-59,cruise missile,"air-launched, air-to-surface, anti-ship, land-...",154,141,269.0,166.0,154.0,0.0,100.0,0.27,61.71,2022-09-28,2025-10-15
14,Orlan-10,UAV,reconnaissance,201,175,267.0,266.0,201.0,0.0,100.0,0.26,99.63,2022-09-30,2026-01-09
15,Supercam,UAV,reconnaissance,178,160,252.0,251.0,178.0,0.0,100.0,0.25,99.60,2023-04-08,2025-06-29
16,X-47 Kinzhal,ballistic missile,air-launched,70,65,225.0,64.0,70.0,0.0,100.0,0.22,28.44,2023-01-26,2026-03-28
17,Iskander-K,cruise missile,Unknown type,59,59,212.0,139.0,59.0,0.0,100.0,0.21,65.57,2023-05-17,2026-04-02
18,X-22,cruise missile,air-to-surface,38,37,157.0,3.0,38.0,0.0,100.0,0.16,1.91,2022-10-09,2026-03-09
19,X-101/X-555 and Kalibr and X-59/X-69,cruise missile,Unknown type,2,2,157.0,126.0,2.0,0.0,100.0,0.16,80.25,2024-08-26,2025-09-09

In [6]:
con.sql("""
SELECT *
FROM mart_area_macro_summary
ORDER BY launched_total DESC
""").df()

,area_macro,target_scope,attack_rows,active_days,launched_total,destroyed_total,launched_share_pct
0,nationwide,nationwide,1485,817,90589.0,65050.0,89.85
1,south,directional_or_other_macro,973,521,5627.0,5602.0,5.58
2,south,specific_area_rows,526,338,1430.0,947.0,1.42
3,multi,specific_area_rows,57,50,875.0,589.0,0.87
4,north,specific_area_rows,53,42,572.0,514.0,0.57
5,center-east,specific_area_rows,175,141,314.0,214.0,0.31
6,east,specific_area_rows,97,79,295.0,97.0,0.29
7,east,directional_or_other_macro,91,62,281.0,175.0,0.28
8,multi,directional_or_other_macro,9,9,241.0,187.0,0.24
9,unknown,unknown,30,21,192.0,133.0,0.19
10,west,directional_or_other_macro,8,8,94.0,91.0,0.09
11,center-west,specific_area_rows,14,13,73.0,51.0,0.07
12,south-east,specific_area_rows,29,21,66.0,29.0,0.07
13,north-east,specific_area_rows,20,18,54.0,25.0,0.05
14,south-east,directional_or_other_macro,5,5,34.0,33.0,0.03
15,west,specific_area_rows,8,8,32.0,16.0,0.03
16,north,directional_or_other_macro,7,7,28.0,21.0,0.03
17,center,specific_area_rows,3,3,7.0,5.0,0.01
18,international,specific_area_rows,2,2,6.0,1.0,0.01
19,front line,directional_or_other_macro,2,1,5.0,5.0,0.00
20,north-east,directional_or_other_macro,2,1,5.0,5.0,0.00
21,center,directional_or_other_macro,1,1,5.0,5.0,0.00

In [7]:
con.sql("SELECT * FROM vw_dashboard_daily_activity LIMIT 20").df()

,event_date,attack_rows,distinct_weapon_models,launched_total,destroyed_total,not_reach_goal_total,still_attacking_total,launched_7d_avg,destroyed_7d_avg
0,2022-09-28,2,2,8.0,7.0,0.0,0.0,8.000000,7.000000
1,2022-09-29,1,1,7.0,5.0,0.0,0.0,7.500000,6.000000
2,2022-09-30,1,1,3.0,3.0,0.0,0.0,6.000000,5.000000
3,2022-10-01,1,1,1.0,1.0,0.0,0.0,4.750000,4.000000
4,2022-10-02,1,1,7.0,5.0,0.0,0.0,5.200000,4.200000
5,2022-10-05,3,2,8.0,8.0,0.0,0.0,5.666667,4.833333
6,2022-10-06,6,3,17.0,17.0,0.0,0.0,7.285714,6.571429
7,2022-10-07,1,1,3.0,3.0,0.0,0.0,6.571429,6.000000
8,2022-10-08,2,2,3.0,3.0,0.0,0.0,6.000000,5.714286
9,2022-10-09,3,3,22.0,1.0,0.0,0.0,8.714286,5.428571
10,2022-10-10,3,3,108.0,56.0,0.0,0.0,24.000000,13.285714
11,2022-10-11,4,2,62.0,54.0,0.0,0.0,31.857143,20.285714
12,2022-10-12,2,2,19.0,19.0,0.0,0.0,33.428571,21.857143
13,2022-10-13,2,2,11.0,11.0,0.0,0.0,32.571429,21.000000
14,2022-10-14,1,1,8.0,8.0,0.0,0.0,33.285714,21.714286
15,2022-10-15,1,1,6.0,6.0,0.0,0.0,33.714286,22.142857
16,2022-10-16,1,1,11.0,11.0,0.0,0.0,32.142857,23.571429
17,2022-10-17,5,3,39.0,39.0,0.0,0.0,22.285714,21.142857
18,2022-10-18,3,3,11.0,11.0,0.0,0.0,15.000000,15.000000
19,2022-10-19,3,2,29.0,27.0,0.0,0.0,16.428571,16.142857

In [11]:
con.sql("""
SELECT table_schema, table_name
FROM information_schema.tables
ORDER BY table_schema, table_name;
""").df()

   table_schema                       table_name
0          main          mart_area_macro_summary
1          main              mart_daily_activity
2          main   mart_directional_macro_summary
3          main            mart_overview_summary
4          main             mart_region_activity
5          main        mart_weapon_model_summary
6          main         mart_weapon_type_summary
7          main            silver_attack_regions
8          main                   silver_attacks
9          main          silver_weapon_reference
10         main         vw_dashboard_area_macros
11         main      vw_dashboard_daily_activity
12         main  vw_dashboard_directional_macros
13         main            vw_dashboard_overview
14         main          vw_dashboard_region_map
15         main       vw_dashboard_weapon_models
16         main        vw_dashboard_weapon_types

In [12]:
con.sql("SELECT * FROM vw_dashboard_overview LIMIT 20").df()

,first_event_date,last_event_date,total_attack_rows,distinct_event_dates,distinct_weapon_models,distinct_weapon_categories,total_launched,total_destroyed,total_not_reach_goal,total_still_attacking,nationwide_launched_total,specific_area_launched_total,unknown_target_rows,unmatched_weapon_reference_rows
0,2022-09-28,2026-04-10,3597,1066,70,7,100825.0,73795.0,13052.0,499.0,90589.0,3724.0,30.0,9.0

In [17]:
con.sql("SELECT * FROM silver_attacks LIMIT 50 ").df()

,source_file,source_row_number,event_date,time_start,time_end,weapon_model,weapon_model_key,weapon_category,weapon_type,weapon_national_origin,...,num_hit_location,num_fall_fragment_location,carrier,turbojet,turbojet_destroyed,affected_region,destroyed_details,launched_details,launch_place_details,source
0,missile_attacks_daily.csv,1,2026-04-10,2026-04-10 18:00,2026-04-11 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,10,11,<NA>,<NA>,<NA>,,"{'south': 58, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid032X1Jf7NWioks9KTaTsxizU2ybk...
1,missile_attacks_daily.csv,2,2026-04-09,2026-04-09 18:00,2026-04-10 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,6,7,<NA>,<NA>,<NA>,,"{'south': 65, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid0pQnYhBKpjgREd3gkKksxC2cTpzf...
2,missile_attacks_daily.csv,3,2026-04-10,2026-04-10,2026-04-10,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid032X1Jf7NWioks9KTaTsxizU2...
3,missile_attacks_daily.csv,4,2026-04-08,2026-04-08 18:00,2026-04-09 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,11,4,<NA>,<NA>,<NA>,,"{'south': 27, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid0j4r3zJU8WKaasb8Li1ZCNpPvR3N...
4,missile_attacks_daily.csv,5,2026-04-09,2026-04-09,2026-04-09,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid07SozPwK38SCTkN32qiUtjmge...
5,missile_attacks_daily.csv,6,2026-04-07,2026-04-07 18:00,2026-04-08 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,12,1,<NA>,<NA>,<NA>,,"{'south': 36, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid085wVNfiuaWoeSMUCKKHn7hj4DZT...
6,missile_attacks_daily.csv,7,2026-04-08,2026-04-08,2026-04-08,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid0voLLotajLXktWuVuZfCPttWB...
7,missile_attacks_daily.csv,8,2026-04-06,2026-04-06 18:00,2026-04-07 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,14,9,<NA>,<NA>,<NA>,,"{'south': 33, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid029ChaUPjzpwopc8Nc55FYMoLcVU...
8,missile_attacks_daily.csv,9,2026-04-07,2026-04-07,2026-04-07,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid0329VM51VQdtvSkEQDUE8aB1f...
9,missile_attacks_daily.csv,10,2026-04-05,2026-04-05 18:00,2026-04-06 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,17,13,<NA>,<NA>,<NA>,,"{'south': 27, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid02gDwFJsin3E2C3hcK2ajX2ZozXC...
10,missile_attacks_daily.csv,11,2026-04-06,2026-04-06,2026-04-06,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid02Diuw9mDn1K3EMnjm9iafkav...
11,missile_attacks_daily.csv,12,2026-04-04,2026-04-04 18:00,2026-04-05 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,10,3,<NA>,<NA>,<NA>,,"{'south': 30, 'east': 85, 'north': NaN}",,,kpszsu/posts/pfbid0pZC4FfgZfabzw5M8mcecr3wQJhy...
12,missile_attacks_daily.csv,13,2026-04-05,2026-04-05,2026-04-05,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid06sptk5uPtBPECH36W4r64c5h...
13,missile_attacks_daily.csv,14,2026-04-03,2026-04-03 18:00,2026-04-04 07:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,10,6,<NA>,<NA>,<NA>,,"{'south': 30, 'east': 74, 'north': NaN}",,,kpszsu/posts/pfbid0Zqw4QDwQKFFLc216BsXbzMcxfo4...
14,missile_attacks_daily.csv,15,2026-04-04,2026-04-04,2026-04-04,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid02FBfDLZcgjx6zDsuHcKumn6j...
15,missile_attacks_daily.csv,16,2026-04-02,2026-04-02 18:00,2026-04-03 14:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,20,22,<NA>,<NA>,<NA>,,"{'south': 139, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid0h9ELiXekqMep7BQKWSNmQ66aT9A...
16,missile_attacks_daily.csv,17,2026-04-02,2026-04-02 18:00,2026-04-03 14:00,Iskander-M,iskander-m,ballistic missile,"TV-guided, tactical",russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,kpszsu/posts/pfbid0h9ELiXekqMep7BQKWSNmQ66aT9A...
17,missile_attacks_daily.csv,18,2026-04-02,2026-04-02 18:00,2026-04-03 14:00,Iskander-K,iskander-k,cruise missile,,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,kpszsu/posts/pfbid0h9ELiXekqMep7BQKWSNmQ66aT9A...
18,missile_attacks_daily.csv,19,2026-04-03,2026-04-03 09:00,2026-04-03 11:30,X-101/X-555,x-101/x-555,cruise missile,air-launched,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,kpszsu/posts/pfbid0h9ELiXekqMep7BQKWSNmQ66aT9A...
19,missile_attacks_daily.csv,20,2026-04-03,2026-04-03,2026-04-03,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid02pWncvkYFyNCBBamUKuRUWRQ...
20,missile_attacks_daily.csv,21,2026-04-01,2026-04-01 18:00,2026-04-02 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,12,8,<NA>,<NA>,<NA>,,"{'south': 153, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid02qkkmtbzSFLPdKcg9EzEHFmNX1A...
21,missile_attacks_daily.csv,22,2026-04-02,2026-04-02,2026-04-02,X-31,x-31,cruise missile,air-to-surface,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid02mA4mPPr6goSAY782it3ECmc...
22,missile_attacks_daily.csv,23,2026-04-01,2026-04-01 08:00,2026-04-01 18:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,<NA>,<NA>,<NA>,<NA>,<NA>,,"{'south': NaN, 'west': 28, 'east': NaN, 'north...",,,kpszsu/posts/pfbid03MvpSHyZaaoDd992QrhibGiqqsV...
23,missile_attacks_daily.csv,24,2026-03-31,2026-03-31 18:00,2026-04-01 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,11,5,<NA>,<NA>,<NA>,,"{'south': 54, 'west': 29, 'east': 135, 'north'...",,,kpszsu/posts/pfbid0uvmLnU6yGQLraSh11aka8VqDZr2...
24,missile_attacks_daily.csv,25,2026-04-01,2026-04-01,2026-04-01,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid0hnMtZjLpxkQBYvEUJZ1dzRPr...
25,missile_attacks_daily.csv,26,2026-03-30,2026-03-30 18:00,2026-03-31 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,11,6,<NA>,<NA>,<NA>,,"{'south': 54, 'east': NaN, 'north': NaN}",,,kpszsu/posts/pfbid02HfGVgRccfqa9wgbU7r7mg2vfiT...
26,missile_attacks_daily.csv,27,2026-03-31,2026-03-31,2026-03-31,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid01TjaKLAmBJYMi3QQTHA5a3tK...
27,missile_attacks_daily.csv,28,2026-03-29,2026-03-29 18:00,2026-03-30 08:30,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,7,2,<NA>,<NA>,<NA>,,"{'south': 34, 'east': 144, 'north': NaN}",,,kpszsu/posts/pfbid02HWy59nceGsMrER1KzAS7uU9Mqg...
28,missile_attacks_daily.csv,29,2026-03-30,2026-03-30,2026-03-30,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid02bgr2615zidWHPSvXnLqdRE4...
29,missile_attacks_daily.csv,30,2026-03-28,2026-03-28 18:00,2026-03-29 09:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,7,14,<NA>,<NA>,<NA>,,"{'south': 97, 'west': 5, 'east': 114, 'north':...",,,kpszsu/posts/pfbid02HWy59nceGsMrER1KzAS7uU9Mqg...
30,missile_attacks_daily.csv,31,2026-03-29,2026-03-29,2026-03-29,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid0ZGcujHzEcC7ANaXnYPVd522p...
31,missile_attacks_daily.csv,32,2026-03-29,2026-03-29,2026-03-29,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvkZahid/posts/pfbid0uYpAqjQGfdje3noCGMaGCkGor...
32,missile_attacks_daily.csv,33,2026-03-29,2026-03-29,2026-03-29,Reconnaissance UAV,reconnaissance uav,UAV,reconnaissance,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid0ZGcujHzEcC7ANaXnYPVd522p...
33,missile_attacks_daily.csv,34,2026-03-29,2026-03-29,2026-03-29,Iskander-M,iskander-m,ballistic missile,"TV-guided, tactical",russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid0ZGcujHzEcC7ANaXnYPVd522p...
34,missile_attacks_daily.csv,35,2026-03-28,2026-03-28 21:00,2026-03-28 21:20,X-47 Kinzhal,x-47 kinzhal,ballistic missile,air-launched,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,kpszsu/posts/pfbid02HWy59nceGsMrER1KzAS7uU9Mqg...
35,missile_attacks_daily.csv,36,2026-03-27,2026-03-27 18:00,2026-03-28 07:30,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,18,9,<NA>,<NA>,<NA>,,"{'south': 115, 'east': 103, 'north': NaN}",,,kpszsu/posts/pfbid02rer2ssAL3SJpTNdNXdjH7J24JE...
36,missile_attacks_daily.csv,37,2026-03-28,2026-03-28,2026-03-28,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid03NN4EASFwPPAGCNxenG1BtwY...
37,missile_attacks_daily.csv,38,2026-03-26,2026-03-26 18:00,2026-03-27 08:30,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,8,4,<NA>,<NA>,<NA>,,"{'south': 14, 'east': 107, 'north': NaN}",,,kpszsu/posts/pfbid035BkMPb39RvUgrogPU1m18WVsij...
38,missile_attacks_daily.csv,39,2026-03-27,2026-03-27,2026-03-27,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid034ASuxmrdAd6fT5V5nEvUoNf...
39,missile_attacks_daily.csv,40,2026-03-25,2026-03-25 18:00,2026-03-26 08:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,11,5,<NA>,<NA>,<NA>,,"{'south': 41, 'east': 58, 'north': NaN}",,,kpszsu/posts/pfbid02VbSRHXHbdtxeSDssamTdfudj7b...
40,missile_attacks_daily.csv,41,2026-03-26,2026-03-26,2026-03-26,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid02f3tjAZCskXepycD1VMCD5jg...
41,missile_attacks_daily.csv,42,2026-03-24,2026-03-24 19:00,2026-03-25 08:30,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,18,3,<NA>,<NA>,<NA>,,"{'south': 81, 'east': 67, 'north': NaN}",,,kpszsu/posts/pfbid02amYjoDfAxakDmHHKx3b7DxXVGa...
42,missile_attacks_daily.csv,43,2026-03-25,2026-03-25,2026-03-25,Unknown UAV,unknown uav,UAV,,,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid0Udk3XPGhbx775sFgD6hj4ubH...
43,missile_attacks_daily.csv,44,2026-03-24,2026-03-24 09:00,2026-03-24 18:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,<NA>,<NA>,<NA>,<NA>,<NA>,,"{'south': NaN, 'west': NaN, 'east': 104, 'nort...",,,kpszsu/posts/pfbid0BSYYGMWNyoRHhckgZZcJsFn1VVQ...
44,missile_attacks_daily.csv,45,2026-03-23,2026-03-23 18:00,2026-03-24 09:00,X-59/X-69,x-59/x-69,cruise missile,,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,{'south': 2},,,kpszsu/posts/pfbid0Fq1AmLQAEt3L6f6hSCZnknoViPB...
45,missile_attacks_daily.csv,46,2026-03-23,2026-03-23 18:00,2026-03-24 09:00,X-31,x-31,cruise missile,air-to-surface,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,PvKPivden/posts/pfbid0yuJayBbJVqBCuefwrfdbeHkZ...
46,missile_attacks_daily.csv,47,2026-03-23,2026-03-23 18:00,2026-03-24 09:00,Shahed-136/131,shahed-136/131,UAV,loitering munition,iran,...,22,10,<NA>,<NA>,<NA>,"['Ivano-Frankivsk oblast', 'Zaporizhzhia oblas...","{'south': 81, 'west': 11, 'east': 128, 'north'...",,,kpszsu/posts/pfbid0Fq1AmLQAEt3L6f6hSCZnknoViPB...
47,missile_attacks_daily.csv,48,2026-03-23,2026-03-23 18:00,2026-03-24 09:00,Iskander-K,iskander-k,cruise missile,,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,kpszsu/posts/pfbid0Fq1AmLQAEt3L6f6hSCZnknoViPB...
48,missile_attacks_daily.csv,49,2026-03-23,2026-03-23 18:00,2026-03-24 09:00,C-400 and Iskander-M,c-400 and iskander-m,surface-to-air and ballistic,,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,,,,kpszsu/posts/pfbid0Fq1AmLQAEt3L6f6hSCZnknoViPB...
49,missile_attacks_daily.csv,50,2026-03-24,2026-03-24 04:30,2026-03-24 05:30,X-101/X-555,x-101/x-555,cruise missile,air-launched,russia,...,<NA>,<NA>,<NA>,<NA>,<NA>,,{'south': 10},,,kpszsu/posts/pfbid0Fq1AmLQAEt3L6f6hSCZnknoViPB...